<?php
/** Datos de marca, herencia de ficha y trazabilidad física de NexoPC. */
if (!defined('ABSPATH')) exit;

function nexopc_traceability_install() {
    global $wpdb;
    $charset = $wpdb->get_charset_collate();
    $prefix = $wpdb->prefix . 'nexopc_';
    $wpdb->query("CREATE TABLE IF NOT EXISTS {$prefix}marcas (id bigint unsigned NOT NULL AUTO_INCREMENT, nombre varchar(120) NOT NULL, slug varchar(120) NOT NULL, sitio_oficial varchar(255) NULL, soporte_url varchar(255) NULL, activo tinyint(1) NOT NULL DEFAULT 1, PRIMARY KEY (id), UNIQUE KEY slug (slug)) $charset");
    $wpdb->query("CREATE TABLE IF NOT EXISTS {$prefix}producto_marca (product_id bigint unsigned NOT NULL, marca_id bigint unsigned NOT NULL, PRIMARY KEY (product_id), KEY marca_id (marca_id)) $charset");
    $wpdb->query("CREATE TABLE IF NOT EXISTS {$prefix}politicas_serie (product_id bigint unsigned NOT NULL, politica varchar(32) NOT NULL DEFAULT 'none', PRIMARY KEY (product_id)) $charset");
    $wpdb->query("CREATE TABLE IF NOT EXISTS {$prefix}unidades_inventario (id bigint unsigned NOT NULL AUTO_INCREMENT, sellable_id bigint unsigned NOT NULL, serial_numero varchar(191) NULL, serial_normalizado varchar(191) NULL, estado varchar(32) NOT NULL DEFAULT 'available', origen varchar(32) NOT NULL DEFAULT 'stock', proveedor varchar(191) NULL, recibido_at datetime NULL, garantia_hasta date NULL, notas text NULL, created_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY serial_normalizado (serial_normalizado), KEY sellable_estado (sellable_id,estado)) $charset");
    $wpdb->query("CREATE TABLE IF NOT EXISTS {$prefix}pedido_item_unidad (id bigint unsigned NOT NULL AUTO_INCREMENT, order_item_id bigint unsigned NOT NULL, unidad_id bigint unsigned NOT NULL, asignado_at datetime NOT NULL, asignado_por bigint unsigned NULL, PRIMARY KEY (id), UNIQUE KEY unidad_id (unidad_id), KEY order_item_id (order_item_id)) $charset");
}
add_action('plugins_loaded', 'nexopc_traceability_install', 27);

function nexopc_brand_for_product($product_id) { global $wpdb; $p=$wpdb->prefix.'nexopc_'; return $wpdb->get_row($wpdb->prepare("SELECT b.id,b.nombre,b.slug,b.sitio_oficial AS sitioOficial,b.soporte_url AS soporteUrl FROM {$p}producto_marca pm JOIN {$p}marcas b ON b.id=pm.marca_id WHERE pm.product_id=%d",$product_id),ARRAY_A) ?: null; }
function nexopc_brands_list() { global $wpdb; $rows=$wpdb->get_results("SELECT id,nombre,slug,sitio_oficial AS sitioOficial,soporte_url AS soporteUrl FROM {$wpdb->prefix}nexopc_marcas WHERE activo=1 ORDER BY nombre",ARRAY_A); return rest_ensure_response(array('items'=>$rows)); }
function nexopc_brand_save(WP_REST_Request $request) { global $wpdb; $data=nexopc_request_data($request); $name=sanitize_text_field($data['nombre']??''); if(!$name)return nexopc_error('nexopc_brand_name_required','El nombre de la marca es obligatorio.',422,array('nombre'=>'El nombre es obligatorio.')); $result=$wpdb->insert($wpdb->prefix.'nexopc_marcas',array('nombre'=>$name,'slug'=>sanitize_title($data['slug']??$name),'sitio_oficial'=>esc_url_raw($data['sitioOficial']??''),'soporte_url'=>esc_url_raw($data['soporteUrl']??''))); if(!$result)return nexopc_error('nexopc_brand_save_failed','No se pudo guardar la marca.',422); return rest_ensure_response(nexopc_brand_for_id($wpdb->insert_id)); }
function nexopc_brand_for_id($id) { global $wpdb; return $wpdb->get_row($wpdb->prepare("SELECT id,nombre,slug,sitio_oficial AS sitioOficial,soporte_url AS soporteUrl FROM {$wpdb->prefix}nexopc_marcas WHERE id=%d",$id),ARRAY_A); }
function nexopc_set_product_brand($product_id,$brand_id) { global $wpdb; $brand_id=absint($brand_id); $table=$wpdb->prefix.'nexopc_producto_marca'; if(!$brand_id){$wpdb->delete($table,array('product_id'=>$product_id));return true;} if(!nexopc_brand_for_id($brand_id))return nexopc_error('nexopc_invalid_brand','Selecciona una marca válida.',422,array('brandId'=>'Selecciona una marca de la lista.')); $wpdb->replace($table,array('product_id'=>$product_id,'marca_id'=>$brand_id));return true; }

function nexopc_serial_policy_for_product($product_id) { global $wpdb; return $wpdb->get_var($wpdb->prepare("SELECT politica FROM {$wpdb->prefix}nexopc_politicas_serie WHERE product_id=%d",$product_id)) ?: 'none'; }
function nexopc_set_serial_policy($product_id,$policy) { global $wpdb; $policy=in_array($policy,array('none','optional','required_on_dispatch','required_on_receipt'),true)?$policy:'none'; $wpdb->replace($wpdb->prefix.'nexopc_politicas_serie',array('product_id'=>$product_id,'politica'=>$policy));return true; }
function nexopc_hardware_effective_item($product_id) { $own=nexopc_hardware_product_item($product_id); if($own){$own['inheritsParent']=false;return $own;} $product=wc_get_product($product_id); if($product && $product->is_type('variation')){ $parent=nexopc_hardware_product_item($product->get_parent_id()); if($parent){$parent['inheritsParent']=true;$parent['parentProductId']=$product->get_parent_id();return $parent;} } return null; }

function nexopc_inventory_units_list(WP_REST_Request $request) { global $wpdb; $id=absint($request->get_param('sellableId')); $where=$id?$wpdb->prepare(' WHERE sellable_id=%d',$id):''; $rows=$wpdb->get_results("SELECT id,sellable_id AS sellableId,serial_numero AS serialNumero,estado,origen,proveedor,recibido_at AS recibidoAt,garantia_hasta AS garantiaHasta,notas FROM {$wpdb->prefix}nexopc_unidades_inventario$where ORDER BY id DESC LIMIT 100",ARRAY_A); return rest_ensure_response(array('items'=>$rows)); }
function nexopc_inventory_unit_save(WP_REST_Request $request) { global $wpdb; $data=nexopc_request_data($request); $sellable=absint($data['sellableId']??0); if(!$sellable || !wc_get_product($sellable)) return nexopc_error('nexopc_invalid_sellable','Selecciona un producto o variante válido.',422); $serial=sanitize_text_field($data['serialNumero']??''); $normalized=$serial?strtoupper(preg_replace('/\s+/', '',$serial)):null; $status=in_array($data['estado']??'available',array('expected','available','reserved','assigned','shipped','returned'),true)?$data['estado']:'available'; $result=$wpdb->insert($wpdb->prefix.'nexopc_unidades_inventario',array('sellable_id'=>$sellable,'serial_numero'=>$serial?:null,'serial_normalizado'=>$normalized,'estado'=>$status,'origen'=>sanitize_key($data['origen']??'stock'),'proveedor'=>sanitize_text_field($data['proveedor']??''),'recibido_at'=>!empty($data['recibidoAt'])?sanitize_text_field($data['recibidoAt']):null,'garantia_hasta'=>!empty($data['garantiaHasta'])?sanitize_text_field($data['garantiaHasta']):null,'notas'=>sanitize_textarea_field($data['notas']??''),'created_at'=>current_time('mysql',true))); if(!$result)return nexopc_error('nexopc_inventory_unit_save_failed','No se pudo guardar la unidad. El número de serie ya podría estar registrado.',422); return rest_ensure_response(array('id'=>(int)$wpdb->insert_id),201); }
function nexopc_assign_inventory_unit(WP_REST_Request $request) { global $wpdb; $data=nexopc_request_data($request); $order=wc_get_order(absint($request['id'])); $item_id=absint($data['orderItemId']??0); $unit_id=absint($data['unitId']??0); if(!$order || !$item_id || !$unit_id)return nexopc_error('nexopc_assignment_invalid','Selecciona un pedido, una línea y una unidad válidos.',422); $item=$order->get_item($item_id); if(!$item)return nexopc_error('nexopc_order_item_not_found','La línea no pertenece al pedido.',404); $sellable=absint($item->get_variation_id()?:$item->get_product_id()); $unit=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}nexopc_unidades_inventario WHERE id=%d",$unit_id)); if(!$unit || (int)$unit->sellable_id!==$sellable)return nexopc_error('nexopc_unit_mismatch','La unidad no corresponde al producto o variante de esta línea.',422); if(!in_array($unit->estado,array('available','reserved'),true))return nexopc_error('nexopc_unit_unavailable','La unidad ya no está disponible para asignar.',422); $wpdb->insert($wpdb->prefix.'nexopc_pedido_item_unidad',array('order_item_id'=>$item_id,'unidad_id'=>$unit_id,'asignado_at'=>current_time('mysql',true),'asignado_por'=>get_current_user_id()?:null)); if(!$wpdb->rows_affected)return nexopc_error('nexopc_unit_assignment_failed','La unidad ya fue asignada a otro pedido.',422); $wpdb->update($wpdb->prefix.'nexopc_unidades_inventario',array('estado'=>'assigned'),array('id'=>$unit_id)); return rest_ensure_response(array('orderId'=>$order->get_id(),'orderItemId'=>$item_id,'unitId'=>$unit_id,'status'=>'assigned'));
}
function nexopc_validate_order_serials_before_dispatch($order) { global $wpdb; foreach($order->get_items() as $item){ $sellable=absint($item->get_variation_id()?:$item->get_product_id()); $policy=nexopc_serial_policy_for_product($sellable); if($policy==='none' && $item->get_variation_id()) $policy=nexopc_serial_policy_for_product($item->get_product_id()); if(!in_array($policy,array('required_on_dispatch','required_on_receipt'),true)) continue; $assigned=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}nexopc_pedido_item_unidad WHERE order_item_id=%d",$item->get_id())); if($assigned<(int)$item->get_quantity()) return nexopc_error('nexopc_serial_required','No puedes completar el pedido: faltan números de serie asignados.',422); } return true; }
